apiVersion: v1
kind: PersistentVolume
metadata:
  name: project206-pv-db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data