apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: production
spec:
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: website
        image: wordpress
        env:
          - name: WORDPRESS_DB_HOST
            value: "..........."

          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name:  my-secret
                key: user

          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  my-secret
                key: userpassword

          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name:  my-secret
                key: database
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        
        ports:
        - containerPort: 80
