apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  db_root: R00tP@ssw0rd!
  db_password: P@ssw0rd!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  db_host: "my-db-svc"
  database: "phonebook"
  db_user: "mehmet"