apiVersion: v1
kind: Secret
metadata:
  name: envfrom-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: R00tP@ssw0rd!
  MYSQL_PASSWORD: P@ssw0rd!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envfrom-configmap
data:
  MYSQL_DATABASE: phonebook
  MYSQL_USER: mehmet