apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: role-for-junior
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: [""]
  verbs: ["get", "create", "list"]