apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  rootpassword: UXdlcjEyMzQ=
  userpassword: TWVobWV0MjAu
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  databasename: phonebook
  username: mehmet
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  MYSQL_DATABASE_HOST: mysql-service
  MYSQL_USER: mehmet
  MYSQL_DATABASE: phonebook
