apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UXdlcjEyMzQ=
  MYSQL_PASSWORD: TWVobWV0MjAu
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  MYSQL_DATABASE: phonebook
  MYSQL_USER: mehmet
