apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - name: resultserver-pods
        image: mehmet2020/result-server
        envFrom:
          - configMapRef:
              name: server-config
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: userpassword
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: resultserver-service
spec:
  type: NodePort
  selector:
    app: resultserver
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002

        # env:
        #   - name: MYSQL_DATABASE_HOST
        #     value: mysql-service
        #   - name: MYSQL_USER
        #     value: mehmet 
        #   - name: MYSQL_PASSWORD
        #     value: Mehmet20.  
        #   - name: MYSQL_DATABASE
        #     value: phonebook