apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: web-server
        image: mehmet2020/web-server
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: secret-for-db
        - configMapRef:
            name: db-config
            