- name: Configure PostGreSql node
  hosts: _ansible_postgresql
  become: true
  vars_files:
    - secret.yaml
  tasks:
    - name: Update Packages
      yum:  
        name: "*"
        state: latest
    - name: Uninstall old versions
      yum:
        name: "{{ item }}"
        state: removed
      loop:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
    - name: Add Docker-Repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo 
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
    - name: Install pip
      package:
        name: python3-pip
        state: latest
    - name: Install Docker SDK
      pip:
        name: docker
       
    - name: add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: start docker service
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: Create build directory
      file:
        path: /home/ec2-user/postgresql
        state: directory
        owner: root
        group: root
        mode: "0755" 
    - name: copy the sql script
      copy: 
        src: /home/ec2-user/ansible/ansible-project/postgres/init.sql
        dest: /home/ec2-user/postgresql
    - name: copy the dockerfile
      copy: 
        src: /home/ec2-user/ansible/ansible-project/postgres/Dockerfile
        dest: /home/ec2-user/postgresql 

    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name=mehmet_postgre' && docker stop mehmet_postgre && docker rm -fv mehmet_postgre && docker image rm -f mehmetcw/postgre || echo 'Not Found'"

    - name: build container image
      docker_image:
        name: mehmetcw/postgre
        build:
          path: /home/ec2-user/postgresql
        source: build
        state: present

    - name: create postgresql docker container
      docker_container:
        name: mehmet_postgre
        image: mehmetcw/postgre
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "{{ password }}"
        volumes:
          - /db-data:/var/lib/postgresql/data
      register: container_info

    - name: print the container info
      debug:
        var: container_info

    