apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  namespace: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp
    spec:
      # terminationGracePeriodSeconds: 60 serviceden cikarilan podun kac saniye sonra terminate edilecegini belirtir.
      containers:                      # default 30s
      - name: myapp
        image: ozgurozturknet/k8s:v1
        livenessProbe:
          httpGet:
            path: /healthcheck     # localhostta bu path'a request gonderiliriyor.her uygulamada ayri
            port: 80
          initialDelaySeconds: 5 # pod calismaya basladiktan sonra on hazirllik icin bekleme suresi
          periodSeconds: 5        # kac saniyede bir /healthcheck'e gidilecek
        readinessProbe:
          httpGet:
            path: /ready     
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 3    
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
