apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment-deneme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-deneme
  template:
    metadata:
      labels:
        app: webserver-deneme
    spec:
      containers:
      - name: webserver-pods-deneme
        image: mehmet2020/deneme
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service-deneme
spec:
  type: NodePort
  selector:
    app: webserver-deneme
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003

